# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ada8b8460947023e93cddf0394519ebb30a65214dc37d84da30266b365322ee48609b5b2a6b76217e7f29b97bec7319edffd14a9753493d187fccb02d2b6d4d6

test:
  secret_key_base: 1ca771b335f7265f30acdfdfe99da9e29f4405f90dc3bd61c09a1d575e86f2a2f603af9ca58b835643ad6964a378166e8a9081c71e0f1d707cb42e57f2dd1c16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
